name: MonsterMadness
version: ${project.version}
main: labs.madskwerl.monstermadness.MonsterMadness
api-version: 1.13
authors: [madskwerl]
description: Kill All Ze Monsters

commands:
  WOP:
    description: Get a WOP
    usage: /WOP
  KIT:
    description: Get Charges Artifacts
    usage: /KIT
  PU:
    description: Get a Powerup
    usage: /PU